import Image from "next/image";

export function Contributors() {
  return (
    <div>
      <a
        href="https://github.com/fiatjaf"
        className="mr-2 inline-block h-8 w-8 rounded-full"
        data-hovercard-type="user"
        data-hovercard-url="/users/fiatjaf/hovercard"
        data-octo-click="hovercard-link-click"
        data-octo-dimensions="link_type:self"
      >
        <Image
          src="https://avatars.githubusercontent.com/u/1653275?s=64&amp;v=4"
          width={64}
          height={64}
          alt="@fiatjaf"
          className="rounded-full"
        />
      </a>
      <a
        href="https://github.com/scsibug"
        className="mr-2 inline-block h-8 w-8 rounded-full"
        data-hovercard-type="user"
        data-hovercard-url="/users/scsibug/hovercard"
        data-octo-click="hovercard-link-click"
        data-octo-dimensions="link_type:self"
      >
        <Image
          src="https://avatars.githubusercontent.com/u/57707?s=64&amp;v=4"
          alt="@scsibug"
          width={64}
          height={64}
          className="rounded-full"
        />
      </a>
      <a
        href="https://github.com/melvincarvalho"
        className="mr-2 inline-block h-8 w-8 rounded-full"
        data-hovercard-type="user"
        data-hovercard-url="/users/melvincarvalho/hovercard"
        data-octo-click="hovercard-link-click"
        data-octo-dimensions="link_type:self"
      >
        <Image
          src="https://avatars.githubusercontent.com/u/65864?s=64&amp;v=4"
          alt="@melvincarvalho"
          width={64}
          height={64}
          className="rounded-full"
        />
      </a>
      <a
        href="https://github.com/hieblmi"
        className="mr-2 inline-block h-8 w-8 rounded-full"
        data-hovercard-type="user"
        data-hovercard-url="/users/hieblmi/hovercard"
        data-octo-click="hovercard-link-click"
        data-octo-dimensions="link_type:self"
      >
        <Image
          src="https://avatars.githubusercontent.com/u/18631614?s=64&amp;v=4"
          alt="@hieblmi"
          width={64}
          height={64}
          className="rounded-full"
        />
      </a>
      <a
        href="https://github.com/srid"
        className="mr-2 inline-block h-8 w-8 rounded-full"
        data-hovercard-type="user"
        data-hovercard-url="/users/srid/hovercard"
        data-octo-click="hovercard-link-click"
        data-octo-dimensions="link_type:self"
      >
        <Image
          src="https://avatars.githubusercontent.com/u/3998?s=64&amp;v=4"
          alt="@srid"
          width={64}
          height={64}
          className="rounded-full"
        />
      </a>
      <a
        href="https://github.com/asoltys"
        className="mr-2 inline-block h-8 w-8 rounded-full"
        data-hovercard-type="user"
        data-hovercard-url="/users/asoltys/hovercard"
        data-octo-click="hovercard-link-click"
        data-octo-dimensions="link_type:self"
      >
        <Image
          src="https://avatars.githubusercontent.com/u/7641?s=64&amp;v=4"
          alt="@asoltys"
          width={64}
          height={64}
          className="rounded-full"
        />
      </a>
      <a
        href="https://github.com/jb55"
        className="mr-2 inline-block h-8 w-8 rounded-full"
        data-hovercard-type="user"
        data-hovercard-url="/users/jb55/hovercard"
        data-octo-click="hovercard-link-click"
        data-octo-dimensions="link_type:self"
      >
        <Image
          src="https://avatars.githubusercontent.com/u/45598?s=64&amp;v=4"
          alt="@jb55"
          width={64}
          height={64}
          className="rounded-full"
        />
      </a>
      <a
        href="https://github.com/schulterklopfer"
        className="mr-2 inline-block h-8 w-8 rounded-full"
        data-hovercard-type="user"
        data-hovercard-url="/users/schulterklopfer/hovercard"
        data-octo-click="hovercard-link-click"
        data-octo-dimensions="link_type:self"
      >
        <Image
          src="https://avatars.githubusercontent.com/u/397451?s=64&amp;v=4"
          alt="@schulterklopfer"
          width={64}
          height={64}
          className="rounded-full"
        />
      </a>
      <a
        href="https://github.com/GlenCooper"
        className="mr-2 inline-block h-8 w-8 rounded-full"
        data-hovercard-type="user"
        data-hovercard-url="/users/GlenCooper/hovercard"
        data-octo-click="hovercard-link-click"
        data-octo-dimensions="link_type:self"
      >
        <Image
          src="https://avatars.githubusercontent.com/u/967793?s=64&amp;v=4"
          alt="@GlenCooper"
          width={64}
          height={64}
          className="rounded-full"
        />
      </a>
      <a
        href="https://github.com/Kukks"
        className="mr-2 inline-block h-8 w-8 rounded-full"
        data-hovercard-type="user"
        data-hovercard-url="/users/Kukks/hovercard"
        data-octo-click="hovercard-link-click"
        data-octo-dimensions="link_type:self"
      >
        <Image
          src="https://avatars.githubusercontent.com/u/1818366?s=64&amp;v=4"
          alt="@Kukks"
          width={64}
          height={64}
          className="rounded-full"
        />
      </a>
      <a
        href="https://github.com/verretor"
        className="mr-2 inline-block h-8 w-8 rounded-full"
        data-hovercard-type="user"
        data-hovercard-url="/users/verretor/hovercard"
        data-octo-click="hovercard-link-click"
        data-octo-dimensions="link_type:self"
      >
        <Image
          src="https://avatars.githubusercontent.com/u/10324237?s=64&amp;v=4"
          alt="@verretor"
          width={64}
          height={64}
          className="rounded-full"
        />
      </a>
    </div>
  );
}
